### ISSUE TITLE
AT - Can't submit multiple values

### ISSUE THREAD

**Issue by simondate** [danielstorey/adapt-dragndrop#2]
https://github.com/danielstorey/adapt-dragndrop/blob/master/properties.schema#L51-L64

Multiple words don't work in AT. Need to add a bit extra here.

**Comment by simondate** [comment]
Sorry, I'm gonna close as I think this was an issue fixed in a more recent version of the AT. See https://github.com/adaptlearning/adapt_authoring/issues/2134

**Comment by danielstorey** [comment]
ok, cheers @simondate , I was gonna say - I tested it fairly recently and everything seemed to work

**Comment by simondate** [comment]
I think I was testing on maybe like v0.4 or something? Will have to work around it I think 😞
